### ISSUE TITLE
how to configure MQTT broker with user and pass

### ISSUE THREAD

**Issue by jorge-teixeira** [kd8bxp/Simple-Moving-Message-WIFI-Display#1]
my broker MQTT have user and pass.. how do i connect to him?

**Comment by kd8bxp** [comment]
You'll want to look at the documentation of the pubsubclient library.
https://github.com/knolleary/pubsubclient
https://pubsubclient.knolleary.net/api.html
I believe what you are looking for is at line 141 needs to be changed.
and I think you just need to add the username and password
client.connect (clientID, username, password)
